### ISSUE TITLE
Exclude columns

### ISSUE THREAD

**Issue by gfkeogh** [serilog-contrib/serilog-sinks-azuretablestorage#102]
Could you please add an `excludeColumns` feature to complement the `propertyColumns`?

In my case for example, I would like to exclude the `EventTime`, `MessageTemplate` and `Data` columns because they contain verbose duplicate or excess information.

Thanks, *Greg*
<https://www.orthogonal.net.au/>

**Comment by pwelter34** [comment]
You can implement IDocumentFactory to customize the document created.  Use DefaultDocumentFactory as an example.

**Comment by gfkeogh** [comment]
Thanks, I missed the importance of IDocumentFactory, I think the word 'Document' made me think it was for something else. other can generating custom table entities. You probably should mention in the documentation that implementing that interface gives you complete control over the creation of the table entities.

**Comment by Gaz83** [comment]
Can you post an example on this? I created a copy of DefaultDocumentFactory and commented out the following in the Create()

//tableEntity["Data"] = writer.ToString();

Deleted the Table and redeployed my app and I see the Data column is still there but is filled with null values.

**Comment by gfkeogh** [comment]
My full code is too customised to paste here, but in a nutshell it goes like the following. Pass your class that implements `IDocumentFactory` into the create.

```
Log.Logger = new LoggerConfiguration()
	.ReadFrom.Configuration(configuration)
	.WriteTo.AzureTableStorage(
		"{YOURCONNECT}",
		storageTableName: "{YOURNAME}",
		documentFactory: new YourDocfacClass()
	)
	.CreateLogger();
```

The factory class simply converts one `LogEvent` into an Azure `TableEntity`. Below I assume a log property named 'ThreadId' is always present to convert.  The convert code is a bit verbose so you'll probably want to make some helper (or extension) methods to reduce the clutter. The class `LogEventPropertyValue` is really confusing and I luckily found samples of how to cast it to `ScalarValue` and `StructureValue` (and others) to get the values, otherwise I would have had no idea at all how to proceed (it's terrible class design). You will need extra logic to deal with null values.

```
internal class YourDocfacClass : IDocumentFactory
{
  public TableEntity Create(LogEvent logEvent, AzureTableStorageSinkOptions options, IKeyGenerator keyGenerator)
  {
    var row = new TableEntity();
    row.PartitionKey = "{YOURPK}";
    row.RowKey = "{YOURRK}";
    row.Timestamp = logEvent.Timestamp;
    // -- ThreadId --
    LogEventPropertyValue lepv = logEvent.Properties["ThreadId"];
    var scalar = (ScalarValue)lepv;
    row["ThreadId"] = (int)scalar.Value!;
    // -- Convert more log properties to row properties --
    return row;
  }
}
```
