### ISSUE TITLE
Error writing debug events to table storage

### ISSUE THREAD

**Issue by mterwoord** [serilog-contrib/serilog-sinks-azuretablestorage#103]
**Description**
I'm trying to write (for now) debug level logging to azure table storage. On my development PC (Windows 10), this works. Pushing the changes to an Azure Container App instance, I get the following error, after configuring Table storage to be in the Audit pipeline of serilog:
```The batch request contains multiple changes with same row key. An entity can appear only once in a batch request```

I don't want/need it in the Audit pipeline, just normal WriteTo is fine, but this way it's easier for me to see errors.

**Reproduction**
In the logging configuration, use the following code:
```csharp
                                 .UseSerilog((hostingContext, loggerConfig) =>
                                             {
                                                 var connectionString = hostingContext.Configuration.GetConnectionString("SerilogAzureTableStorage");
                                                 loggerConfig.ReadFrom.Configuration(hostingContext.Configuration)
                                                             .WriteTo.AzureTableStorage(connectionString, LogEventLevel.Debug);
                                             })
````

**Expected behavior**
Logs turning up in the table storage.

**Relevant package, tooling and runtime versions**
Serilog.Sinks.AzureTableStorage, version 9.0.0

**Additional context**

**Comment by pwelter34** [comment]
This should be fixed in v9.4.1.  Thanks
