### ISSUE TITLE
Timestamp ignore

### ISSUE THREAD

**Issue by marcomezzanotte** [serilog-contrib/serilog-sinks-azuretablestorage#25]
Hi, I'm playing with your sink and I noticed that LogEvent timestamp is ignored and completely managed by AzureTables. This behavior is also reported by official [MSDN](https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.storage.table.itableentity.timestamp.aspx) documentation.

Can you please consider to deal with this issue? My temporary workaround is to add a custom field to the row.

Thanks.

 @pandazzurro

**Comment by Vlad-Stryapko** [comment]
I've encountered this issue as well. I don't think there there is anything that can be done except for probably introducing sink-specific name for timestamp if it's possible.  Right now I'm using a custom enricher which adds timestamps.

**Comment by pwelter34** [comment]
Added EventTime property to address this in version 8.
