### ISSUE TITLE
Support for a KeyGenerator in the app settings?

### ISSUE THREAD

**Issue by vmary2014** [serilog-contrib/serilog-sinks-azuretablestorage#37]
Hi
I am trying to override the rowkey generation by implementing my own `IKeyGenerator` interface.
However, my application is currently configured using the application settings, using the `Serilog.Settings.AppSettings` package. 
I would like to be able to set the KeyGenerator parameter in the configuration using something like this:
`<add key="database:serilog:write-to:AzureTableStorageWithProperties.keyGenerator" value="**_The class name_**" />`

Is that possible ?
Thanks
Vincent

**Comment by formix** [comment]
@vmary2014, see my [Stackoverflow answer](https://stackoverflow.com/a/46083183/780036), use the "<Full Class Name>, <Assembly Name>" format in your value.

ex:  `MyApp.Serilog.AzureTableStorage.MyKeyGenerator, MyApp`
