### ISSUE TITLE
EmitBatchAsync Failed some times

### ISSUE THREAD

**Issue by AugustoFaria** [serilog-contrib/serilog-sinks-azuretablestorage#40]
Hello, 

Im using serilog-sinks-azuretablestorage for log my aplication events. Im using writeInBatches.

Is a payment aplication that i need to log every steps on azure, the aplication is using 3G connection and developed on .net core 1.1

What is happen is that some times is not logging on azure table storage. Im using the code like that:

`new LoggerConfiguration()
                .MinimumLevel.Debug()
                .Enrich.FromLogContext()
                .Enrich.WithMachineName()
                .Enrich.WithEnvironmentUserName()
                .WriteTo.AzureTableStorageWithProperties(
                    dao.StorageAccount,
                    storageTableName: dao.TableReference,
                    restrictedToMinimumLevel: LogEventLevel.Warning,
                    writeInBatches: true,
                    batchPostingLimit: dto.BatchPostingLimit,
                    formatProvider: new CultureInfo("pt-BR"),
                    period: dto.Period)
                 .WriteTo.RollingFile(new JsonFormatter(), _localPath, LogEventLevel.Warning)
                 .WriteTo.Console()
                 .CreateLogger();`

The default batchPostingLimit is 100 and period i set to 5 minutes. One transaction have 50 lines more less.

Someone knows what is happen?

Thx.

**Comment by nblumhardt** [comment]
Hi - does `SelfLog` show any errors? https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

Cheers,
Nick

**Comment by AugustoFaria** [comment]
Hi Nick thx for the reply. 

No dont have any error. But i think, maybe because the app is running in a self service kiosk machine, they could shutdown the machine before the app upload the data. I tested without connection and when is back the app upload the remained transactions. 

But im thinking to put some contingency for this situation.

Regards
Augusto

**Comment by pwelter34** [comment]
The Sink in version 8 has been rewritten.  Batch write is now on by default.   Make sure to call Log.CloseAndFlush(); on application close.  Please reopen if still an issue
