### ISSUE TITLE
LoggerSinkConfiguration.AzureTableStorage() doesn't work with batchPostingLimit>100

### ISSUE THREAD

**Issue by mchenx** [serilog-contrib/serilog-sinks-azuretablestorage#44]
I noticed LoggerSinkConfiguration.AzureTableStorage method can also accept parameters as LoggerSinkConfiguration.AzureTableStorageWithProperties method does. However, with batchPostingLimit value > 100 provided, AzureTableStorage methodd won't push logs to Azure table storage at all, it only works when batchPostingLimit is <=100.

I'm wondering why AzureTableStorage accepts the parameters like batchPostingLimit parameter?
And  why we need two names: AzureTableStorage, AzureTableStorageWithProperties, wouldn't that be a good idea to have one method name but different signatures (input parameters)?

**Comment by siewers** [comment]
Looking at the implementation, there is a hard limit of 100 operations per batch: https://github.com/serilog/serilog-sinks-azuretablestorage/blob/8e9cc8a51e8ba2bbe2d39b8a85410dbb1dafcfa6/src/Serilog.Sinks.AzureTableStorage/Sinks/AzureTableStorage/AzureBatchingTableStorageSink.cs#L85

**Comment by ThomasPe** [comment]
There's a hard limit of max 100 items per patch on the Azure Table Storage side, so checking this beforehand in the code is reasonable IMO. Can be closed?
