### ISSUE TITLE
Using context properties when using AzureTableStorageWithProperties

### ISSUE THREAD

**Issue by farzadmf** [serilog-contrib/serilog-sinks-azuretablestorage#45]
Hi,

I'm trying to use `AzureTableStorageWithProperties`, and I have a property that's attached to the context; something like this:

```cs
using (LogContext.PushProperty("CameraId", camera.Id)
{
  /* ... */
}
```

So, I was wondering how I can configure the logger to consider this property and create a column for it when it's present on the context.

I tried this, but it doesn't seem to be working:

```cs
Log.Logger = new LoggerConfiguration()
  .ReadFrom.Configuration(configuration)
  .WriteTo.AzureTableStorageWithProperties(
    "my-connection-string",
    storageTableName: "mytable",
    propertyColumns: new[] { "CameraId" })
  .CreateLogger();
```

Also, as you may have noticed, I'm using [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration), so I was hoping you can tell me how I can put it into my `appsettings.json` too.

Thank you

**Comment by farzadmf** [comment]
Actually, the first part of my question is solved (I had to include `Enrich.FromLogContext`, but the last part of the question is still an issue: is there a way to specify `propertyColumns` in `appsettings.json`?

**Comment by cdavid** [comment]
I have not given it a shot, but here is something you could try (I wrap the table sink in an Async sink).

Also, not sure if you know this, but by default (when using the "non-WithProperties" sink) ALL additional enriched properties show up in the table. When you use the "WithProperties", you constrain the logs to show just a subset of all properties (the relevant code is in (`\src\Serilog.Sinks.AzureTableStorage\Sinks\AzureTableStorageWithProperties\AzureTableStorageEntityFactory.cs :: CreateEntityWithProperties()`).

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.Async", "Serilog.Sinks.AzureTableStorage" ],
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "AzureTableStorageWithProperties",
              "Args": {
                "connectionString": "my-connection-string",
                "storageTableName": "mytable",
                "propertyColumns": [ "CameraId" ]
            }
          ]
        }
    ],
    "Enrich": [ "FromLogContext" ]
  }
}
```

**Comment by farzadmf** [comment]
Thank you @cdavid ; I'm going to give it a try, maybe using `Async` will work.

And as for the "non-WithProperties" sink, the only thing with that is that all the properties are put into the `Data` column, so somehow I wanted to have separate columns for the ones I care about.

And, I think, the "WithProperties" sink also contains all the properties, but it puts them into `AggregateProperties" column

**Comment by Jaffacakes82** [comment]
@farzadmf did you get anywhere with this? I can't get the AzureTableStorageWithProperties sink to work at all, nor can I get any additional properties logging using the AzureTableStorage sink, even with the inclusion of Enrich.LogFromContext().

**Comment by pwelter34** [comment]
The sink has been rewritten in version 8.0.   Please open new issue if still having problems
