### ISSUE TITLE
WithProperties sink not working in ASP.NET Core 2.1 app

### ISSUE THREAD

**Issue by Jaffacakes82** [serilog-contrib/serilog-sinks-azuretablestorage#60]
Hi,

I'm trying to use the 'AzureTableStorageWithProperties' sink in my ASP.NET Core 2.1.3 application. I've added the Serilog configuration to my appsettings.json file as follows:

```json
"Serilog": {
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "AzureTableStorageWithProperties",
        "Args": {
          "storageTableName": "logs",
          "connectionString": "MyConnectionString"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
    "Properties": {
      "Application": "My App"
    }
}
```

And configured my logger in my `Startup.cs - ConfigureServices()` method class like so:
```csharp
Log.Logger = new LoggerConfiguration().ReadFrom.Configuration(this.Configuration).CreateLogger();
```

The above configuration doesn't work - I get no logs in my Azure Table. If I change the sink to 'AzureTableStorage' it does work, but does not include the 'RequestId' column which is the one I'm after.

Does this sink fully support ASP.NET Core 2.1.3? Any ideas?

Thanks.

**Comment by ozkank** [comment]
@Jaffacakes82 Is there any progress about this issue on ASP.NET CORE 2.1?

**Comment by Jaffacakes82** [comment]
> @Jaffacakes82 Is there any progress about this issue on ASP.NET CORE 2.1?

@ozkank I haven't heard anything back and didn't manage to get this working. I am using the configuration out of the box which seems to work but extending new fields didn't work.

**Comment by ozkank** [comment]
I want to use same implementation. I need to store the log files on Azure tables. I'll be glad if you share your solution. Thanks.
