### ISSUE TITLE
No information if connection to Table Storage failed

### ISSUE THREAD

**Issue by Structed** [serilog-contrib/serilog-sinks-azuretablestorage#61]
Is there a way to see if the Logger actually connected to Azure Table Storage?
We haven't found any indicator, other than the app taking longer to start and of course no logs coming in to the Table Storage.

If not, is this perhaps possible to implement?

**Comment by pwelter34** [comment]
If you configure  Serilog SelfLog like so ...

```c#
Serilog.Debugging.SelfLog.Enable(Console.Error);
```

You will see something like this ...

```
2023-04-16T23:40:06.9656663Z Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink: Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)
```
