### ISSUE TITLE
Is it possible to add fixed column values without using root-level Serilog properties?

### ISSUE THREAD

**Issue by daiplusplus** [serilog-contrib/serilog-sinks-azuretablestorage#64]
My website writes to multiple Serilog sinks and I'd like to include deployment-specific information in the Azure Table Storage-logged events which would be redundant in the other sinks - and I'd like them to be stored in their own Table Storage columns regardless of whether the code is using `WriteTo.AzureTableStorage` or `WriteTo.AzureTableStorageWithProperties`

I understand I could use a child Serilog log sink that adds the properties so other sinks wouldn't see them, but that still doesn't allow me to promote those properties to their own table columns.

Ideally, I'd like to see `IKeyGenerator` extended with a new method:

    interface IKeyGenerator {
        IReadOnlyDictionary<String,String> GenerateAdditionalColumnValues( LogEvent logEvent )
    }

Thoughts?

**Comment by pwelter34** [comment]
Sink has ben rewritten in version 8.  You can now fully customize how the document is create by implementing IDocumentFactory.
