### ISSUE TITLE
Using CloudTable instead of CloudStorageAccount

### ISSUE THREAD

**Issue by mattosaurus** [serilog-contrib/serilog-sinks-azuretablestorage#68]
Hi,

Is there a reason CloudStorageAccount is used to get a reference to the logging table rather than directly accepting a reference to CloudTable? This feels like we're granting more permissions than necessary. If the table exists then this should be enough, if it doesn't exist then a reference to CloudTableClient should be enough to create it.

Thanks

**Comment by kashifsoofi** [comment]
Sounds like a good suggestion, unfortunately I don't have access to Azure resources anymore so I wouldn't be able to test it.

A PR would be more than welcome.

**Comment by mattosaurus** [comment]
Thanks, I'll submit one when I get some free time.

**Comment by mattosaurus** [comment]
I've created a PR adding this functionality, let me know if you see any issues or require any changes.

**Comment by pwelter34** [comment]
Project has been updated to the latest SDK in version 7.x.
