### ISSUE TITLE
WindowsAzure.Storage 9.3.3 depreciation

### ISSUE THREAD

**Issue by a-martynov** [serilog-contrib/serilog-sinks-azuretablestorage#75]
WindowsAzure.Storage package is deprecated. This library has been split into multiple parts and replaced.
Do you have plans to switch to the actual Azure packages ?

**Comment by miltonhowe** [comment]
bump

**Comment by rbonini** [comment]
Indeed. Came here to ask the same question

**Comment by chrisAretoNet** [comment]
bumo

**Comment by ThomasPe** [comment]
Should be fixed since 6.0.0-dev-00146 with the switch to Microsoft.Azure.Cosmos.Table
