### ISSUE TITLE
Why is this sink not async?

### ISSUE THREAD

**Issue by jean-paul-scorito** [serilog-contrib/serilog-sinks-azuretablestorage#79]
Hi!

I might be wrong about this but from my perspective this library can be, and should be async, you never want a logging to throttle your application.
Am I missing some greater picture problem here?

Or would it be in place to create a PR with a async version of this library?

is the library still actively being maintained?

**Comment by craniodev** [comment]
I had the same problem. 
I solved using the package [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async)

**Comment by jean-paul-scorito** [comment]
I did the same indeed! Still wondering why it isnt async by default

Outlook for Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by ThomasPe** [comment]
I think this is a valid feature request we should take a look at.

**Comment by pwelter34** [comment]
The sink in version 8 has been updated to use batch async by default.
