### ISSUE TITLE
A new organization for this repository

### ISSUE THREAD

**Issue by nblumhardt** [serilog-contrib/serilog-sinks-azuretablestorage#83]
Hi @serilog/reviewers-azure-table-storage 👋 

Via https://github.com/serilog/serilog/issues/1627 - we're unbundling the `serilog` organization to help distribute the effort involved in managing the various Serilog sub-projects. The `serilog` organization will now only manage the fundamental sinks and other packages that the rest of the ecosystem builds upon.

If this package is actively maintained, it can be moved to a new organization managed by the maintainers. Otherwise, it can move to the `serilog-archive` parking lot, from where we hope a new community-run fork might spring from in the future 🌷 .

Let me know if you're a maintainer and keen to continue this project under a new org; otherwise, I'll shuffle things around and move this one to the archive.

Thanks!

**Comment by pwelter34** [comment]
If it gets moved to serilog-contrib, I'd be willing to help be a maintainer.  I think serilog-contrib is the best location for discoverability and to remain available as maintainers come and go.

**Comment by heroes3lover** [comment]
very looking forward as #82 sitting there for ages.
Company wants to remove the deperated WindowsAzure.Storage packages.

**Comment by ThomasPe** [comment]
I'd be in as well if help is needed @nblumhardt

**Comment by nblumhardt** [comment]
Thanks for all the offers of help, we'll see what can be figured out 👍

**Comment by nblumhardt** [comment]
Alrighty folks! I'll move this and serilog-sinks-azuretablestorage to serilog-contrib (both have active contributors), and get maintenance kicked back off over there. 👍

**Comment by pwelter34** [comment]
@nblumhardt Awesome, thanks for moving.  However, I don't have access.   Maybe I need to be added to the serilog-contrib org?

Once i get access, i'll get started on cleaning up.   I'll update the build to use github actions.

thanks again

**Comment by nblumhardt** [comment]
Thanks for the note @pwelter34 - I'm just in the process of confirming with @augustoproiete how we should set teams up over there in contrib, I'll drop a note on this thread when it's ready to go.

**Comment by nblumhardt** [comment]
I'm sorry it's taken so long. @pwelter34 @ThomasPe you should both now have received invitations to become maintainers in this repository. I'm keen to get the ball rolling and can help out with bits and pieces in the short term :-)

A good course of action might now be to close this ticket, and open a new one with a "get the ball rolling again" checklist, including things like reviewing/merging open PRs, triaging issues, and getting CI set up in the new org.

Sound like a plan? 😎

**Comment by ThomasPe** [comment]
Sounds great, thanks so much for making this happen. Should I start with creating a new ToDO issue?
How will we handle CD, I assume we can continue update the available NuGet package? Then we would need an access token to set up an action. But this is probably a discussion for the new topic as well. :)

**Comment by nblumhardt** [comment]
Creating the new TODO issue sounds like the way to go :+1:

I've just done some work setting up Serilog.Sinks.ApplicationInsights in serilog-contrib, using GitHub Actions for CI. It would be fairly easy to copy `Build.ps1` and `.github` over from that repository to get things rolling, here.

I've added a NuGet API key now to this repository's secrets, as `NUGET_API_KEY`, which the Actions setup I mentioned above will be able to consume.

**Comment by pwelter34** [comment]
I'll get the build going.  I'll also merge in the PR for Azure.Data.Tables.  We can assess from there.

**Comment by pwelter34** [comment]
- New build has been created
- bummed the version to 7.0
- beta nuget packages are published to github feed
- add target for .net 6
- cleaned up all build warnings and errors
- add issue for features in version 7.0

**Comment by nblumhardt** [comment]
Awesome :-) Guess it's time to close this, then!
