### ISSUE TITLE
Move tests to Azurite

### ISSUE THREAD

**Issue by ThomasPe** [serilog-contrib/serilog-sinks-azuretablestorage#85]
As the Azure Storage Emulator [is deprecated it](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator) I think it makes sense to switch it out for the newer [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) in the integration tests. 

I'd need to check how to best get it running automatically like it used to.

**Comment by pwelter34** [comment]
This is completed with new build, v7.x
