### ISSUE TITLE
Serilog.Sinks.AzureTableStorage nuget package for V6.0.0 release not available

### ISSUE THREAD

**Issue by Bertk** [serilog-contrib/serilog-sinks-azuretablestorage#88]
nuget.org has only a pre-release of [Serilog.Sinks.AzureTableStorage](
https://www.nuget.org/packages/Serilog.Sinks.AzureTableStorage/6.0.0-dev-00146) V6.0.0. 
This version uses the meanwhile deprecated package `Microsoft.Azure.Cosmos.Table`. 

Please upload a release version which refers actual client library `Azure.Data.Tables`.

**Comment by paynesworld** [comment]
+1 for this please.  Looking to remove dependencies on the old Azure.Data.Tables library.  Thank you!

**Comment by lucengelhardt** [comment]
+1 for this please! We really want to upgrade to the latest client libraries.
