### ISSUE TITLE
Sinks should implement IDisposable

### ISSUE THREAD

**Issue by paynesworld** [serilog-contrib/serilog-sinks-azuretablestorage#89]
According to the "Developing a sink" wiki:
https://github.com/serilog/serilog/wiki/Developing-a-sink#releasing-resources

sinks that implement the IDisposable interface will have Dispose() called when the Log.CloseAndFlush() method is called.  This gives the sink an opportunity make a final/blocking write of any buffered data.  It doesn't appear that the Serilog.Sinks.AzureTableStorage sinks implement this interface, and therefore there's an opportunity for messages to be lost during application shutdown.

I'm calling Log.CloseAndFlush() in my application shutdown code and I'm seeing log messages in my FileLogger location that are being missed in my AzureTableStorage location.  I think this is why.

Thanks much!

**Comment by pwelter34** [comment]
Sink has been updated in version 8 to use the suggested batch technique.
