### ISSUE TITLE
Incompatible with Azure Functions

### ISSUE THREAD

**Issue by kdewey13** [serilog-contrib/serilog-sinks-azuretablestorage#93]
Hi there!

I am attempting to use this sink with an Azure function. Both file and MSSQL sinks are working as expected with the Azure function, but when I add a config section for the Azure Storage Table, nothing is written there. 

I am using this sink with .NET 6.0 minimal web API that is also in my project and it is working correctly. The API and Azure functions are set up the same, so I am at a loss as to why this is working in the API, but not the function, but at the same time, the SQL/file sinks _do_ work in the function. 

Please let me know if I can provide any additional information, thank you!

**Comment by pwelter34** [comment]
Try using the Debug log to see if there are any errors.

Serilog.Debugging.SelfLog.Enable(Console.Error);

**Comment by kdewey13** [comment]
Adding Serilog.Sinks.AzureTableStorage to the usings fixed it! I apologize, for some reason the API worked without the using reference, and I just carried the same config over.
