### ISSUE TITLE
When speficying custom IKeyGenerator no events past 'Now Listening' are logged.

### ISSUE THREAD

**Issue by RoryMcCrossan** [serilog-contrib/serilog-sinks-azuretablestorage#98]
When using the default configuration via appsettings (below) logging to table storage works correctly:

Startup.cs:
```
builder.Host.UseSerilog((context, config) => config.ReadFrom.Configuration(context.Configuration));
```

appsettings.json

```
{
	"AllowedHosts": "*",
	"Serilog": {
		"Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.AzureTableStorage" ],
		"MinimulLevel": {
			"Default": "Information",
			"Override": {
				"Microsoft": "Warning",
				"System": "Warning"
			}
		},
		"WriteTo": [
			{ "Name": "Console" },
			{
				"Name": "AzureTableStorage",
				"Args": {
					"storageTableName": "log",
					"connectionString": "redacted",
				}
			}
		],
		"Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
	}
}
```

Output is as expected:

https://i.imgur.com/KyvJFcr.png

*However*, as soon as I provide a custom IKeyGenerator (in this case I'm actually using a renamed copy of the default one, so as to eliminate any implementation issues on my end), no events are logged past initialisation:

appsettings.json

```
{
	"AllowedHosts": "*",
	"Serilog": {
		"Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.AzureTableStorage" ],
		"MinimulLevel": {
			"Default": "Information",
			"Override": {
				"Microsoft": "Warning",
				"System": "Warning"
			}
		},
		"WriteTo": [
			{ "Name": "Console" },
			{
				"Name": "AzureTableStorage",
				"Args": {
					"storageTableName": "log",
					"connectionString": "redacted",
					"keyGenerator": "Foo.Api.Logging.KeyGenerator.CustomKeyGenerator , Foo.Api" // <-- only change
				}
			}
		],
		"Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
	}
}
```

Customer key generator:

```
public class CustomKeyGenerator : IKeyGenerator
{
    public virtual string GeneratePartitionKey(LogEvent logEvent)
    {
        var utcEventTime = logEvent.Timestamp.UtcDateTime;
        return utcEventTime.GeneratePartitionKey(_options.PartitionKeyRounding);
    }

    public virtual string GenerateRowKey(LogEvent logEvent)
    {
        var utcEventTime = logEvent.Timestamp.UtcDateTime;
        return utcEventTime.GenerateRowKey();
    }
}
```

This is the output, which as you can see is missing all the events shown in the first example. Also, none will be added no matter how I interact with the running API:

https://i.imgur.com/DD1ZH80.png

**Imporrtant**: Note that output to the console still works as expected in both cases, see the expected output (specifically the 'Called!' message, and the ArgumentNullException which I am intentionally throwing)

https://i.imgur.com/q7vOvjJ.png

Further information can be provided if needed. Please advise.

**Comment by RoryMcCrossan** [comment]
I just noticed that this issue is identical to #97, and the fix their works (that being to downgrade to v7.0.25).

Please advise when this regression has been addressed.

**Comment by pwelter34** [comment]
Looking into issue, thanks for reporting
